fieldLayouts:
  4f461624-e059-4d94-9d7c-3d981ecc8758:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1756e5fc-3c34-4a30-bac2-3ab1fa21e122
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4de277ca-9e57-4ef1-adef-e69ee0366f11 # Album Cover
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e0046af-d58b-43e3-8f32-37f85f5bfd6d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b995f631-105e-4801-920c-4638c84eb818 # Record Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40fd1e27-e984-4030-9277-f526dd4025dc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b3613de-abef-4ba9-9cd1-6e18dfbb2803 # Tracks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 709341f1-7488-4aac-86f4-1192deb382d6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 11ad4c65-0c36-45bd-abb9-0cd9267a76fc
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 022167d1-baed-4c79-849d-f34639a8e399 # Albums
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
