fieldLayouts:
  d3e48abf-8821-4a2a-8a51-9b5d5d5c8f65:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6f95dc92-441d-4a6d-8860-4210e2d95f79
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a3563028-ada4-48a6-9ddc-e11314baa01d # Intro Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc6c1d90-3482-44e0-89e4-2c41e4d9a802
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 215508a5-09b9-4508-8338-cdd71db55235
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 2e53d9bf-d50d-44fe-ad95-805fc8eee136 # Articles
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
