defaultPlacement: end
enableVersioning: true
handle: articles
name: Articles
propagationMethod: all
siteSettings:
  152057f2-ce97-47b4-a01b-8cdb4f1217d7: # tryagain
    enabledByDefault: true
    hasUrls: true
    template: articles/_entry
    uriFormat: 'articles/{slug}'
type: channel
